---
flyMSParams: 
    enableBarometer: 1
    enable_gps: 1
    enable_logging: 1
    isDebugMode: 0
    enable_autonomy: 0
    isHeadlessMode: 0
    pitchOffsetDegrees: 0
    rollOffsetDegrees: 0
    yawOffsetDegrees: 0
    alt_KP: 0
    alt_KD: 0
    alt_KI: 0
    roll_KP: 5
    roll_KD: 0.5
    roll_KI: 0.175
    Droll_KP: 0.0155
    Droll_KI: 0.5
    Droll_KD: 0.0012
    max_roll_setpoint: 0.4
    pitch_KP: 5
    pitch_KD: 0.5
    pitch_KI: 0.175
    Dpitch_KP: 0.0155
    Dpitch_KI: 0.5
    Dpitch_KD: 0.0012
    max_pitch_setpoint: 0.4
    yaw_KP: 0.5
    yaw_KI: 0.05
    yaw_KD: 0.05
    max_yaw_rate: 3
    idle_speed: 0.3
    min_throttle: 0.3
    max_throttle: 0.75
    max_vert_velocity: 3
    max_horz_velocity: 3
    aux1: 0
    aux2: 0
    aux3: 0
    aux4: 0
    aux5: 0
    aux6: 0
